curl -w "\n" --data "product_id=1&query=Ainda tem disponivel" "http://localhost:3000"
curl -w "\n" --data "product_id=2&query=quantos disponíveis?" "http://localhost:3000"
curl -w "\n" --data "product_id=10&query=Ainda tem disponivel" "http://localhost:3000"
curl -w "\n" --data "product_id=24&query=Ainda tem?" "http://localhost:3000"
curl -w "\n" --data "product_id=95&query=tem na cor azul? " "http://localhost:3000"
curl -w "\n" --data "product_id=52&query=quanto tempo?" "http://localhost:3000"
curl -w "\n" --data "product_id=14&query=emite nota fiscal?" "http://localhost:3000"
curl -w "\n" --data "product_id=22&query=Ainda tem?" "http://localhost:3000"
curl -w "\n" --data "product_id=2&query=tem na cor rosaroxa? " "http://localhost:3000"
curl -w "\n" --data "product_id=4&query=tem na cor preta? " "http://localhost:3000"
curl -w "\n" --data "product_id=6&query=tem na cor preto? " "http://localhost:3000"
curl -w "\n" --data "product_id=2&query=Ainda tem?" "http://localhost:3000"
curl -w "\n" --data "product_id=63&query=tem na cor amarelo? " "http://localhost:3000"
curl -w "\n" --data "product_id=67&query=quantos disponíveisuhuhsu?" "http://localhost:3000"
curl -w "\n" --data "product_id=38&query= é a prova d'agua?" "http://localhost:3000"
curl -w "\n" --data "product_id=86&query=Ainda tem?" "http://localhost:3000"
curl -w "\n" --data "product_id=23&query= O produto é bom?" "http://localhost:3000"
curl -w "\n" --data "product_id=44&query=O produto é importado?" "http://localhost:3000"
curl -w "\n" --data "product_id=87&query= asdsadasdsadsadas" "http://localhost:3000"
curl -w "\n" --data "product_id=56&query=Ainda tem?" "http://localhost:3000"
curl -w "\n" --data "product_id=27&query= é a prova de agua?" "http://localhost:3000"
curl -w "\n" --data "product_id=43&query=é de qualidade?" "http://localhost:3000"
curl -w "\n" --data "product_id=52&query=tem garantia?" "http://localhost:3000"
curl -w "\n" --data "product_id=75&query= é original?" "http://localhost:3000"
curl -w "\n" --data "product_id=22&query=é importado?" "http://localhost:3000"
curl -w "\n" --data "product_id=44&query= pronta entrega?" "http://localhost:3000"
curl -w "\n" --data "product_id=84&query=Ainda tem?" "http://localhost:3000"
curl -w "\n" --data "product_id=65&query=Tem garantia?" "http://localhost:3000"